title: "@nmicht"
author:
  name: Michelle Torres
  email: hi@michelletorres.dev

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Random thoughts on tech and life.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
#theme: minima

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - about.md

# Set to `true` to show excerpts on the homepage.
show_excerpts: true

# Minima specific settings, which are only available from Minima 3.0 onward.
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic
  
  # Minima date format.
  # The default value is "%b %d, %Y" (e.g. Nov 14, 2023) 
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  date_format: "%Y-%m-%d"

  # Generate social links in footer.
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/michelletorresv", footer: true }
    - { platform: github,         user_url: "https://github.com/nmicht", footer: true }
    - { platform: gitlab,         user_url: "https://gitlab.com/nmicht", footer: false }
    - { platform: devto,          user_url: "https://dev.to/nmicht", footer: false }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/2945909/nmicht", footer: false }
    - { platform: instagram,      user_url: "https://www.instagram.com/nmicht", footer: false }
    - { platform: x,              user_url: "https://x.com/nmicht", footer: true }
    - { platform: spotify,        user_url: "https://open.spotify.com/user/1276838092", footer: false }
    - { platform: goodreads,      user_url: "http://www.goodreads.com/nmicht", footer: false }
    - { platform: amazon,         user_url: "https://www.amazon.de/hz/wishlist/ls/1SZ4R6ZYSMNBC", footer: false }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll", footer: false }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll", footer: false }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll", footer: false }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ", footer: false }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll", footer: false }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll", footer: false }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll", footer: false }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll", footer: false }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb", footer: false }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll", footer: false }